name: aml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.3.1
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - pip:
    - azureml-core==1.42.0
    - azureml-defaults==1.42.0
    - azureml-train-core==1.42.0
    - azureml-train-restclients-hyperdrive==1.42.0
    - tensorflow==2.8.0
    - keras-tuner==1.1.2
    - numpy==1.21.6
    - protobuf==3.20.3  
